# Generated by Django 5.1.6 on 2025-02-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festive', '0002_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=100),
        ),
    ]
