# Generated by Django 5.1.6 on 2025-02-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festive', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
    ]
