# Generated by Django 5.1.6 on 2025-02-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festive', '0005_rename_event_image_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
