# Generated by Django 5.1.6 on 2025-02-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festive', '0006_rename_artist_event_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
