# Generated by Django 5.1.4 on 2025-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festive', '0011_eventmodelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
